name: CI
on:
    push:
        branches:
        - master
    pull_request:
    
jobs:
    pytest:
        name: Pytest
        runs-on: ubuntu-latest
        
        steps:
        -   uses: actions/checkout@v2
        -   name: Install dependencis
            run: |
              python -m pip install --upgrade pip
              pip freeze > requirements.txt
              pip install -r requirements.txt
        -   name: "Test QBMM"
            run: pytest test_qbmm.py
