name: CI
on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  build:
    name: QBMMTest
      runs-on: ubuntu-latest
      steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencis
        run: python -m pip install --upgrade pip; pip install -r requirements.txt
      - name: "Test QBMM"
        run: pytest test/test_qbmm.py
