name: CI
on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip freeze > requirements.txt
        pip install -r requirements.txt
    - name: Test QBMM
      run: cd test && pytest test_qbmm.py



